[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
key = "K"
mode = "~Alt"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["-c", "~/.config/alacritty/clear-focused-tty.sh"]
program = "bash"

[[keyboard.bindings]]
chars = "\r"
key = "K"
mode = "~Alt"
mods = "Control|Shift"

[colors.bright]
black = "#7f8c8d"
blue = "#3daee9"
cyan = "#16a085"
green = "#1cdc9a"
magenta = "#8e44ad"
red = "#c0392b"
white = "#ffffff"
yellow = "#fdbc4b"

[colors.dim]
black = "#31363b"
blue = "#1b668f"
cyan = "#186c60"
green = "#17a262"
magenta = "#614a73"
red = "#783228"
white = "#63686d"
yellow = "#b65619"

[colors.normal]
black = "#232627"
blue = "#1d99f3"
cyan = "#1abc9c"
green = "#11d116"
magenta = "#9b59b6"
red = "#ed1515"
white = "#fcfcfc"
yellow = "#f67400"

[colors.primary]
background = "#232627"
bright_background = "#000000"
bright_foreground = "#ffffff"
dim_background = "#31363b"
dim_foreground = "#eff0f1"
foreground = "#fcfcfc"

[colors.search.focused_match]
background = "#d00000"
foreground = "#ffffff"

[colors.search.matches]
background = "#9ece6a"
foreground = "#000000"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 30000

[keyboard]
